### ISSUE TITLE
Set up test fixture using `caikit_nlp`

### ISSUE THREAD

**Issue by dtrifiro** [vaibhavjainwiz/caikit-nlp-client#11]
We should be able to set up a pytest fixture that sets up a caikit_nlp server instance and use that to test both grpc and http behaviour.

For example, to start a http and grpc server it is sufficient to run:

```bash
RUNTIME_LIBRARY=caikit_nlp python -m caikit.runtime
```

**Comment by z103cb** [comment]
I will take this one.
